### ISSUE TITLE
Change "module instances" to "rules"

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#120]

**Comment by robske110** [comment]
Does this mean we want to change everything referencing modules to rules? - Do we want to break the yaml format for this?
How does this impact / collide with our planned split of modules into a filter step and a change step?

**Comment by JM-Lemmi** [comment]
Not every reference to modules.

A Module is still a Module. Not all current Modules can be converted to the new Filter + Change Type of Module.

Just the specific instance of a Module in a profile will be called a Rule to avoid confusion.

I want to change the yaml too, since I still want the yaml input to be functional in 2.0.

The config.yml.example would then look like this:

```yaml
profiles:
  relay:
    source: "https://example.com/calendar.ics"
    public: true
    immutable-past: true
    admin-tokens:
    - eAn97Sa0BKHKk02O12lNsa1O5wXmqXAKrBYxRcTNsvZoU9tU4OVS6FH7EP4yFbEt
    rules:
    - name: "delete-bysummary-regex"
      regex: "testentry"
      from: "2021-12-02T00:00:00Z"
      until: "2021-12-31T00:00:00Z"
      expires: "2022-12-31T00:00:00Z"
    - name: "add-url"
      url: "https://othersource.com/othercalendar.ics"
      header-Cookie: "MY_AUTH_COOKIE=abcdefgh"
```

So actually the only change here is from `module` -> `rules`
