### ISSUE TITLE
Wrong Title and wrong events in Notification

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#172]
Are we using variables shared between threads, causing confusion?

**Comment by JM-Lemmi** [comment]
The error only appears, if the notifier connects to a local profile.

## Erroring config:

```
version: 2
server:
    addr: :8080
    url: vorlesungsplan.stuvma.de
    loglevel: info
    storagepath: .
    templatepath: ./templates/
    faviconpath: /static/media/favicon.svg
    name: Calendar
    imprintlink: https://stuvma.de/impressum
    privacypolicylink: https://www.stuv-mannheim.de/datenschutzerklaerung/
    mail:
        smtp_server: web10.alfahosting-server.de
        smtp_port: 587
        sender: vorlesungsplan@stuvma.de
        smtp_user: vorlesungsplan@stuvma.de
        smtp_pass: xxx
    super-tokens:
        - xxx
profiles:
    TINF21 CS1:
        sources:
            - https://vorlesungsplan.dhbw-mannheim.de/ical.php?uid=8321001
        public: true
        immutable-past: true
        admin-tokens:
            - xxx
            - xxx
        rules:
            - filters:
                - id: 20230418T090000Z-357244001@group-e.dhbw-mannheim.de
                  type: id
              operator: ""
              action:
                type: delete
    TINF20 AI1:
        sources:
            - https://vorlesungsplan.dhbw-mannheim.de/ical.php?uid=8062001
        public: true
        admin-tokens:
            - xxx
        rules:
            - filters:
                - id: 20230324T083000Z-348943001@group-e.dhbw-mannheim.de
                  type: id
              operator: ""
              action:
                new-description: Wegen Streik auf online verlegt
                new-end: ""
                new-location: Online nicht Raum 160C
                new-start: ""
                new-summary: DB-Implementierungen (online)
                overwrite: "true"
                type: edit
notifiers:
    TINF20 AI1:
        source: http://localhost:8080/profiles/TINF20%20AI1
        interval: 1m
        recipients:
            - jle+ai1@xxx.de
    TINF21 CS1:
        source: http://localhost:8080/profiles/TINF21%20CS1
        interval: 1m
        recipients:
            - s212689@student.dhbw-mannheim.de
```

## Working Config:

```
version: 2
server:
    addr: :8080
    url: vorlesungsplan.stuvma.de
    loglevel: info
    storagepath: .
    templatepath: ./templates/
    faviconpath: /static/media/favicon.svg
    name: Calendar
    imprintlink: https://stuvma.de/impressum
    privacypolicylink: https://www.stuv-mannheim.de/datenschutzerklaerung/
    mail:
        smtp_server: web10.alfahosting-server.de
        smtp_port: 587
        sender: vorlesungsplan@stuvma.de
        smtp_user: vorlesungsplan@stuvma.de
        smtp_pass: xxx
    super-tokens:
        - xxx
notifiers:
    TINF20 AI1:
        source: https://vorlesungsplan.stuvma.de/profiles/TINF20%20AI1
        interval: 1m
        recipients:
            - jle+ai1@xxx.de
    TINF21 CS1:
        source: http://vorlesungsplan.stuvma.de/profiles/TINF21%20CS1
        interval: 1m
        recipients:
            - s212689@student.dhbw-mannheim.de
```
