### ISSUE TITLE
Restructure different edit modes

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#20]
Instead of having to combine multiple filters with multiple profiles chained in a row, the system should accept an "array" of modifiers. Each modifier then has a "mode" and additional arguments that mode needs. An example configuration should look like this:

```
profiles:
   abc:
      url: "https://example.com/calendar.ics"
      passid: true
      modifiers:
      - mode: regex
        regex: "testentry"
        from: "2021-12-02T00:00:00Z"
        until: "2021-12-31T00:00:00Z"
      - mode: delete-id
        id: "testidacb@calendar"
      - mode: add
        url: "https://othersource.com/othercalendar.ics"
      - mode: deduplicate
      - mode: delete
        from: "2019-01-01T00:00:00Z"
        until: "2019-12-31T23:59:59Z"
```

this would enable more modularity for different filtering methods as well as faster processing times.
