### ISSUE TITLE
Multiple filters are not loaded in the config struct

### ISSUE THREAD

**Issue by frereit** [JM-Lemmi/ical-relay#237]
This might be a user error but I am trying to create a simple profile with a single rule with multiple filters:

```yaml
        rules:
            - filters:
                - type: "regex"
                  regex: "testentry"
                  target: "summary"
                - type: "regex"
                  regex: "testentry2"
                  target: "description"
              action:
                type: "delete"
              expires: "2022-12-31T00:00:00Z"
```

I added the following debug logging to the `calendarViewHandler` in `handlers.go` L192:

```golang
	// Log out all rules
	for i, rule := range profile.Rules {
		log.Debug("Rule ", i)
		for j, filter := range rule.Filters {
			log.Debug("Filter ", j, filter)
		}
		log.Debug("Action ", rule.Action)
	}
```

Starting the server and accessing the calender gives the following log:

```
DEBU[0003] Rule 0                                       
DEBU[0003] Filter 0 map[regex:testentry target:summary type:regex] 
DEBU[0003] Action map[type:delete]
```

It seems like only the first filter was loaded into the Rules struct? I started the binary with a clean database and ran `./relay --import-data`.
