### ISSUE TITLE
edit-Modules panic when non-existent property is edited

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#39]
at least this is the bug, I think.

#### config

```yaml
profiles:
  # TINF21CS1 output
  dhbwtinf21cs1:
    source: "http://vorlesungsplan.dhbw-mannheim.de/ical.php?uid=8321001"
    modules:
    - name: "edit-byid"
      id: "20220404T063127Z-324455001@group-e.dhbw-mannheim.de"
      new-location: "Online"
      new-description: "Link folgt"
      overwrite: "false"
```

#### log

```
time="2022-04-20T11:43:08Z" level=info msg="New Request!" client=141.72.155.39 profile=dhbwtinf21cs1
time="2022-04-20T11:43:08Z" level=debug msg="Requested Module: delete-timeframe"
time="2022-04-20T11:43:08Z" level=debug msg="No after time given. Using time 0.\n"
time="2022-04-20T11:43:08Z" level=debug msg="Deleting events between 0001-01-01T00:00:00Z and 2022-04-20T11:43:08Z\n"
time="2022-04-20T11:43:08Z" level=debug msg="Excluding event with id 20220310T182702Z-320898001@group-e.dhbw-mannheim.de\n"
time="2022-04-20T11:43:08Z" level=debug msg="Excluding event with id 20220322T104118Z-321975001@group-e.dhbw-mannheim.de\n"
[...]
time="2022-04-20T11:43:08Z" level=debug msg="Requested Module: delete-bysummary-regex"
time="2022-04-20T11:43:08Z" level=debug msg="Unknown component type ignored: *ics.VTimezone\n"
time="2022-04-20T11:43:08Z" level=debug msg="Requested Module: delete-byid"
time="2022-04-20T11:43:08Z" level=debug msg="Excluding event with id 20220526T140000Z-319977001@group-e.dhbw-mannheim.de\n"
time="2022-04-20T11:43:08Z" level=debug msg="Requested Module: delete-byid"
time="2022-04-20T11:43:08Z" level=debug msg="Excluding event with id 20220422T064500Z-319978001@group-e.dhbw-mannheim.de\n"
time="2022-04-20T11:43:08Z" level=debug msg="Requested Module: edit-byid"
time="2022-04-20T11:43:08Z" level=debug msg="Changing event with id 20220404T063127Z-324455001@group-e.dhbw-mannheim.de"
2022/04/20 11:43:08 http: panic serving 172.18.0.13:38352: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x7e3ea0, 0xb38320})
        /usr/local/go/src/runtime/panic.go:844 +0x258
main.moduleEditId(0xc00038e210, 0xc000178090?)
        /app/modules.go:349 +0x1160
main.callModule(...)
        /app/modules.go:33
main.profileHandler({0x8f1800?, 0xc0003ffc00?}, 0xc00023a800)
        /app/handlers.go:76 +0xada
net/http.HandlerFunc.ServeHTTP(0xc00023a700?, {0x8f1800?, 0xc0003ffc00?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002120c0, {0x8f1800, 0xc0003ffc00}, 0xc00023a600)
        /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc000343e00?}, {0x8f1800, 0xc0003ffc00}, 0xc00023a600)
        /usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000294fa0, {0x8f1ab8, 0xc000179140})
        /usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3071 +0x4db
^C
```
