### ISSUE TITLE
Reuse Filter for a list of URLs/Profiles

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#47]
For example filter all "entfällt" for the list of all dhbw courses

**Comment by JM-Lemmi** [comment]
Maybe do that with an alias function?

**Comment by JM-Lemmi** [comment]
For example like this:

```yaml
module-packs:
  examplepack:
  - name: "delete-bysummary-regex"
    regex: "testentry"
    from: "2021-12-02T00:00:00Z"
    until: "2021-12-31T00:00:00Z"
  - name: "edit-bysuammary-regex"
    regex: "*online"
    new-location: "https://bbb.dhbw.de/room1"

profiles:
  dhbwtinf21cs1:
    [...]
    modules:
    - pack: "examplepack"
```
