### ISSUE TITLE
Generalize Modules

### ISSUE THREAD

**Issue by JM-Lemmi** [JM-Lemmi/ical-relay#66]
Generalize Edit-Modules into Filters and Action:

* Filter: which Events? regex, id, timeframe
* Action: delete, edit overwrite, ...

**Comment by JM-Lemmi** [comment]
There will be different Module Types:

- **Source**: Anything that adds more events to the calendar. URL, File, Caldav other Profiles...
- **Rule**: The Filtering Engine. This will be split into two stages:
  - **Filter**: Choosing which events to apply the rule to. Like Regex, Timeframe, ID, ...
  - **Action**: What effect the rule has: Delete, Edit, Stripinformation, ...
- **Meta**: Meta Modules are Modules that do not change the calendar, but change the way the calendar is processed. Like SaveToFile, SendMail, ...

The restriction of options on the yaml will be more strictly enforced, so that parsing an invalid yaml will be less likely.

**Comment by JM-Lemmi** [comment]
Example config might look like this:

```yaml
profiles:
  relay:
    source: "https://example.com/calendar.ics"
    public: true
    immutable-past: true
    admin-tokens:
    - eAn97Sa0BKHKk02O12lNsa1O5wXmqXAKrBYxRcTNsvZoU9tU4OVS6FH7EP4yFbEt
    modules:
    - filter: "regex"
        regex: "testentry"
        target: "summary"
      filter: "timeframe"
        from: "2021-12-02T00:00:00Z"
        until: "2021-12-31T00:00:00Z"
      action: "delete"
      expires: "2022-12-31T00:00:00Z"
    - source: "https://othersource.com/othercalendar.ics"
      header-Cookie: "MY_AUTH_COOKIE=abcdefgh"
```

**Comment by JM-Lemmi** [comment]
I want this to be in 1.4 to make the import of yaml in 2.0 backwards compatible with a 1.x version.

**Comment by robske110** [comment]
> I want this to be in 1.4 to make the import of yaml in 2.0 backwards compatible with a 1.x version.
Apart from semantics, I don't quite get how doing that changes anything. The BC break will still be there between 1.4 the version before it.

**Comment by JM-Lemmi** [comment]
different mode for stacking filters: logical AND or logical OR

**Comment by JM-Lemmi** [comment]
Option to invert filter

**Comment by JM-Lemmi** [comment]
We need to support multiple filter, action combinations in the rules

```yaml
profiles:
  relay:
    source: "https://example.com/calendar.ics"
    public: true
    immutable-past: true
    admin-tokens:
    - eAn97Sa0BKHKk02O12lNsa1O5wXmqXAKrBYxRcTNsvZoU9tU4OVS6FH7EP4yFbEt
    rules:
      - filters:
        - type: "regex"
          regex: "testentry"
          target: "summary"
        - type: "timeframe"
          from: "2021-12-02T00:00:00Z"
          until: "2021-12-31T00:00:00Z"
        action: "delete"
        expires: "2022-12-31T00:00:00Z"
      - filters:
        - type: "all"
        action: "edit"
          new-summary: "this summary is edited!"
    - source: "https://othersource.com/othercalendar.ics"
      header-Cookie: "MY_AUTH_COOKIE=abcdefgh"
```
